### ISSUE TITLE
 Can't deploy in docker swarm by command "docker stack deploy"

### ISSUE THREAD

**Issue by vinhbuivan** [citusdata/docker#142]
docker-compose.yml
`version: '3.7'
services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:8.3.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
    healthcheck:
  worker:
    image: 'citusdata/citus:8.3.2'
    labels: ['com.citusdata.role=Worker']
    depends_on: manager      
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: master   `

Deploy on stack: `docker stack deploy --compose-file docker-compose.yml citus`

Error message:
`citus_manager.1.fulurfpkdak3@pe-proxy1    | Traceback (most recent call last):
citus_manager.1.fulurfpkdak3@pe-proxy1    |   File "./manager.py", line 97, in <module>
citus_manager.1.fulurfpkdak3@pe-proxy1    |     main()
citus_manager.1.fulurfpkdak3@pe-proxy1    |   File "./manager.py", line 93, in main
citus_manager.1.fulurfpkdak3@pe-proxy1    |     docker_checker()
citus_manager.1.fulurfpkdak3@pe-proxy1    |   File "./manager.py", line 65, in docker_checker
citus_manager.1.fulurfpkdak3@pe-proxy1    |     compose_project = this_container.labels['com.docker.compose.project']
citus_manager.1.fulurfpkdak3@pe-proxy1    | KeyError: 'com.docker.compose.project'
citus_manager.1.w53rff20re6n@pe-proxy1    | connected to master
citus_manager.1.w53rff20re6n@pe-proxy1    | Traceback (most recent call last):
citus_manager.1.w53rff20re6n@pe-proxy1    |   File "./manager.py", line 97, in <module>`

**Comment by vinhbuivan** [comment]
Issues is resolved. Manager node would search for label `com.docker.compose.project` theforce we could do a trick by static asign label for it.

[docker-compose.zip](https://github.com/citusdata/docker/files/3791242/docker-compose.zip)

version: '3.7'
services:
  master:    
    image: 'citusdata/citus:8.3.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master', 'com.docker.compose.project=citus']
    healthcheck:
  worker:
    image: 'citusdata/citus:8.3.2'
    labels: ['com.citusdata.role=Worker', 'com.docker.compose.project=citus']
    depends_on: manager      
  manager:    
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
	labels: ['com.citusdata.role=Manager', 'com.docker.compose.project=citus']
    depends_on: master
